#!/bin/sh
if [ "$USER" = 'discourse' ]; then
    cd /var/www/discourse || exit 1
    RAILS_ENV=production /home/discourse/.rbenv/shims/bundle exec bin/rake "$@"
else
    /usr/bin/sudo -H -i -u discourse -- "$0" "$@"
fi
