---

- name: "create /etc/nginx directory"
  file:
    dest: "/etc/nginx"
    owner: "root"
    group: "root"
    mode: "0700"
    state: "directory"

- name: "install /etc/nginx/nginx.conf"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "nginx upgrade"

- name: "create /etc/nginx/conf.d directory"
  file:
    dest: "/etc/nginx/conf.d"
    owner: "root"
    group: "root"
    mode: "0644"
    state: "directory"

- name: "install /etc/nginx/conf.d/discourse.conf"
  template:
    src: "discourse.conf.j2"
    dest: "/etc/nginx/conf.d/discourse.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "nginx upgrade"

- name: "fix ownership of /var/log/nginx"
  file:
    dest: "/var/log/nginx"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: "0750"
    state: "directory"

- name: "install /etc/logrotate.d/nginx"
  file:
    src: "{{ item }}"
    dest: "/etc/logrotate.d/nginx"
    owner: "root"
    group: "root"
    mode: "0644"
  with_first_found:
    - "logrotate.{{ ansible_os_family }}"

